### PR TITLE
Fix ambiguities in BoundaryTiangulation for AdaptedDiscreteModels

### LINKED ISSUE #1174: Ambiguity with BoundaryTriangulation constructor + AdaptedDiscreteModel
When running the tests of GridapP4est.jl with Julia v1.10.10, I have run into an ambiguity within Gridap (v0.19.5), which I have been able to reproduce with the MWE below. I am bit puzzled that this has bitten me now in GridapP4est, as I did not change a line of code there. @JordiManyer  do you have an idea of what might be the cause? Thanks!

```julia
using Gridap
model = CartesianDiscreteModel((0,1,0,1),(4,4))
fmodel = Gridap.Adaptivity.refine(model)
BoundaryTriangulation(fmodel, Vector{Bool}(undef,num_cells(fmodel)))
```

```
ERROR: MethodError: BoundaryTriangulation(::Gridap.Adaptivity.AdaptedDiscreteModel{2, 2, CartesianDiscreteModel{2, Float64, typeof(identity)}, CartesianDiscreteModel{2, Float64, typeof(identity)}, Gridap.Adaptivity.AdaptivityGlue{Gridap.Adaptivity.RefinementGlue, 2, Vector{Vector{Int64}}, Vector{Int64}, FillArrays.Fill{Gridap.Adaptivity.RefinementRule{Gridap.ReferenceFEs.ExtrusionPolytope{2}}, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.Table{Int64, Vector{Int64}, Vector{Int64}}, FillArrays.Fill{Bool, 1, Tuple{Base.OneTo{Int64}}}}}, ::Vector{Bool}) is ambiguous.

Candidates:
  BoundaryTriangulation(model::Gridap.Adaptivity.AdaptedDiscreteModel, args...; kwargs...)
    @ Gridap.Adaptivity ~/.julia/packages/Gridap/JD3zW/src/Adaptivity/AdaptedTriangulations.jl:101
  BoundaryTriangulation(model::DiscreteModel, face_to_bgface::AbstractVector{<:Integer})
    @ Gridap.Geometry ~/.julia/packages/Gridap/JD3zW/src/Geometry/BoundaryTriangulations.jl:164
  BoundaryTriangulation(model::DiscreteModel, bgface_to_mask::AbstractVector{Bool})
    @ Gridap.Geometry ~/.julia/packages/Gridap/JD3zW/src/Geometry/BoundaryTriangulations.jl:179

Possible fix, define
  BoundaryTriangulation(::Gridap.Adaptivity.AdaptedDiscreteModel, ::AbstractVector{Bool})
```

### PR DESCRIPTION
**Pull request by JordiManyer**
Fixes #1174

### CODE REVIEW

**Comment by JordiManyer** [comment]
@amartinhuertas does this look alright? It should be ok, I think?

File: src/Geometry/BoundaryTriangulations.jl [hunk 1]
```diff
@@ -162,9 +162,8 @@ function BoundaryTriangulation(
 end
 
 function BoundaryTriangulation(
-  model::DiscreteModel,
-  face_to_bgface::AbstractVector{<:Integer})
-  BoundaryTriangulation(model,face_to_bgface,Fill(1,num_facets(model)))
+  model::DiscreteModel, face_to_bgface::AbstractVector{<:Integer}, lcell::Integer=1)
```
Comment (amartinhuertas) [inline src/Geometry/BoundaryTriangulations.jl]: I guess this change is something not related to the ambiguity, but that was somehow missing in the previous version of Gridap?

Comment (JordiManyer) [reply src/Geometry/BoundaryTriangulations.jl]: Yeah, I just saw we had the same signature for bools so I guessed it does not harm to have this one as well.

**Comment by amartinhuertas** [comment]
> @amartinhuertas does this look alright? It should be ok, I think?

Yes, it looks alright to me. I will make some tests as well from GridapP4est and this branch to see if the issue disappears.

**Comment by amartinhuertas** [comment]
> I will make some tests as well from GridapP4est and this branch to see if the issue disappears.

FYI, I have all run all GridapP4est tests and the issue has disappeared (at least as seen from the test stuite).
