### PR TITLE
Uniformly refine unstructured mesh

### LINKED ISSUE #1141: An error occurs when creating test space with `RefinementRule`
Hi! when I was testing my mesh refinement method, an error occured. After briefly checking the source code, I found that `get_face_own_dofs_permutations(::FineToCoarseRefFE,::Conformity)` returns incomplete permutations. My current workaround is to add the following code [here](https://github.com/gridap/Gridap.jl/blob/85a468f1552ca96a7733e0a4130a46ed15c97061/src/Adaptivity/FineToCoarseReferenceFEs.jl#L107),
```julia
ReferenceFEs.get_face_own_dofs_permutations(reffe::FineToCoarseRefFE,conf::Conformity) = get_face_own_dofs_permutations(reffe.reffe,conf)
```
 but I'm not sure if this will cause any unintended side effects.

This issue also exists in the current version. Below is a MWE similar to the [test file](https://github.com/gridap/Gridap.jl/blob/85a468f1552ca96a7733e0a4130a46ed15c97061/test/AdaptivityTests/EdgeBasedRefinementTests.jl#L41).
```julia
# 3 ------ 4
# | \      |
# |   \    |
# |     \  |
# 1 ------ 2

using Gridap
using Gridap.ReferenceFEs
using Gridap.Geometry
using Gridap.Adaptivity
using Gridap.Arrays

conn = [
  [1,2,3],
  [3,2,4]
]
coordinates = VectorValue{2,Float64}[
  (0,0),(1,0),(0,1),(1,1)
]
reffes = [LagrangianRefFE(Float64,TRI,1)]
cell_type = [1,1]
grid = UnstructuredGrid(coordinates,Table(conn),reffes,cell_type)
cm = UnstructuredDiscreteModel(grid)

cells_to_refine = [1]
refinement_method = "barycentric"
fm = refine(cm;cells_to_refine,refinement_method)

glue = get_adaptivity_glue(fm)
rrules = Adaptivity.get_old_cell_refinement_rules(glue)

# error occurs
TestFESpace(cm,rrules,ReferenceFE(lagrangian,Float64,1))
```

The error output is as follows:
```julia
ERROR: BoundsError: attempt to access 1-element Vector{Vector{Int64}} at index [2]
Stacktrace:
  [1] getindex
    @ ./essentials.jl:13 [inlined]
  [2] getindex
    @ ./abstractarray.jl:1293 [inlined]
  [3] getindex!(cache::CachedVector{Int32, Vector{Int32}}, a::Gridap.FESpaces.CellDofsNonOriented, cell::Int64)
    @ Gridap.FESpaces ~/.julia/packages/Gridap/rN56R/src/FESpaces/ConformingFESpaces.jl:558
  [4] _generate_data_and_ptrs_fill_ptrs!(ptrs::Vector{Int32}, vv::Gridap.FESpaces.CellDofsNonOriented)
    @ Gridap.Arrays ~/.julia/packages/Gridap/rN56R/src/Arrays/Tables.jl:180
  [5] generate_data_and_ptrs(vv::Gridap.FESpaces.CellDofsNonOriented)
    @ Gridap.Arrays ~/.julia/packages/Gridap/rN56R/src/Arrays/Tables.jl:161
  [6] Table
    @ ~/.julia/packages/Gridap/rN56R/src/Arrays/Tables.jl:37 [inlined]
  [7] compute_conforming_cell_dofs(cell_fe::CellFE{…}, cell_conformity::CellConformity{…}, grid_topology::UnstructuredGridTopology{…}, face_labeling::FaceLabeling, dirichlet_tags::Vector{…}, dirichlet_components::Nothing)
    @ Gridap.FESpaces ~/.julia/packages/Gridap/rN56R/src/FESpaces/ConformingFESpaces.jl:276
  [8] _ConformingFESpace(vector_type::Type, model::UnstructuredDiscreteModel{…}, face_labeling::FaceLabeling, cell_fe::CellFE{…}, dirichlet_tags::Vector{…}, dirichlet_components::Nothing, trian::BodyFittedTriangulation{…})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/rN56R/src/FESpaces/ConformingFESpaces.jl:149
  [9] FESpace(model::UnstructuredDiscreteModel{…}, cell_fe::CellFE{…}; trian::BodyFittedTriangulation{…}, labels::FaceLabeling, dirichlet_tags::Vector{…}, dirichlet_masks::Nothing, constraint::Nothing, vector_type::Type)
    @ Gridap.FESpaces ~/.julia/packages/Gridap/rN56R/src/FESpaces/FESpaceFactories.jl:23
 [10] FESpace(model::UnstructuredDiscreteModel{…}, cell_reffe::CompressedArray{…}; conformity::Nothing, trian::BodyFittedTriangulation{…}, labels::FaceLabeling, dirichlet_tags::Vector{…}, dirichlet_masks::Nothing, constraint::Nothing, vector_type::Nothing)
    @ Gridap.FESpaces ~/.julia/packages/Gridap/rN56R/src/FESpaces/FESpaceFactories.jl:99
 [11] FESpace(model::UnstructuredDiscreteModel{…}, cell_reffe::CompressedArray{…})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/rN56R/src/FESpaces/FESpaceFactories.jl:65
 [12] TestFESpace(::UnstructuredDiscreteModel{2, 2, Float64, NonOriented}, ::Vararg{Any}; kwargs::@Kwargs{})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/rN56R/src/FESpaces/FESpaceFactories.jl:126
 [13] TestFESpace
    @ ~/.julia/packages/Gridap/rN56R/src/FESpaces/FESpaceFactories.jl:125 [inlined]
 [14] TestFESpace(model::UnstructuredDiscreteModel{…}, rrules::CompressedArray{…}, reffe::Tuple{…}; kwargs::@Kwargs{})
    @ Gridap.Adaptivity ~/.julia/packages/Gridap/rN56R/src/Adaptivity/FineToCoarseReferenceFEs.jl:131
 [15] TestFESpace(model::UnstructuredDiscreteModel{…}, rrules::CompressedArray{…}, reffe::Tuple{…})
    @ Gridap.Adaptivity ~/.julia/packages/Gridap/rN56R/src/Adaptivity/FineToCoarseReferenceFEs.jl:126
```

### LINKED ISSUE #1142: Proposal to Submit a PR for Uniform Mesh Refinement of Unstructured Meshes
Hi, maintainers. I hope this message finds you well. I have been working on implementing a feature for uniform refinement of unstructured 2D and 3D meshes, speciafically for meshes that consist of n-cubes and simplices. Before proceeding to submit a PR,  I wanted to check with you if this feature aligns with the goals and scope of the project.

Implementation Details:
- I have extended the cartesian mesh interface with the function `refine(model::UnstructuredDiscreteModel,n::Int)`, allowing users to refine the mesh to a resolution of `1/n` in a single step.
- At a deeper level, the implementations supports specifying which cells of the mesh should be refined. While this may lead to the creation of hanging nodes, I have kept this behaviour as I believe it could be usefule for future use cases.

Below are some visual examples of the results via refining the mock model.
- Uniformly refine with `n=3`
Image

- Refine `[2,3,4,5]` cells
Image

Please let me know your thoughts. I would be happy to submit a PR for review if you're open to this contribution.

Best regards.

### PR DESCRIPTION
**Pull request by DimhamT**
Hi, maintainers. As described in #1142 , this PR implements uniform refinement method for unstructured meshes that consist of n-cubes and simplexies. The newly introduced interface is `refine(::UnstructuredDiscreteModel,::Int)`.
I would appreciate any feedback on this PR. Thank you!

Closes #1141, closes #1142.

### CODE REVIEW

**Comment by DimhamT** [comment]
Hi, @JordiManyer . Could you please take a look and help review it when you have some time. I’d appreciate your feedback!

The CI is reporting an issue in this PR, but the same checks passed successfully in my forked repository. I’m not sure what’s causing the failure. 

Thanks in advance!

File: src/Adaptivity/UnstructuredUniformRefinement.jl [hunk 1]
```diff
@@ -0,0 +1,545 @@
+# some helper functions
+
+# if `a` is a `CompressedArray`, then replace `b.ptrs` with `a.ptrs`.
+_similar(::AbstractArray,b::CompressedArray) = b
```
Comment (JordiManyer) [inline src/Adaptivity/UnstructuredUniformRefinement.jl:4]: If this is only used in a function, declare it within the function. Let's try to keep the workspace clean.

**Review by JordiManyer — COMMENTED** [review]
Hi @DimhamT thanks for the PR. Two major comments: 

- I think you are overwriting (or very heavily stepping on) pre-existing signatures. Please align you methods with the other ones. 
- I think you are rewriting a lot of code that already exists. I think you can get rid of 50% of what you wrote if you try to reuse what has been done before. I have added comments on where you could look.

**Comment by DimhamT** [comment]
Thanks a lot for reviewing my PR, @JordiManyer ! Sorry for the late reply — I've been caught up with some personal stuff.

> I think you are overwriting (or very heavily stepping on) pre-existing signatures. Please align you methods with the other ones.

I made sure to check the existing function signatures before adding my own, and except for `refine`, I believe I haven't overwritten any others. If  I missed anything or if there's a better way to integrate them, I'm happy to adjust the implementation accordingly.

> I think you are rewriting a lot of code that already exists.

In fact, I've tried to reuse as much of the existing implementation as possible. However, the behavior I'm aiming for differs in some specific ways from the current design, which let me to introduce some modifications. I'll go through each of your comments individualy in follow-up replies to clarify the reasoning.

File: src/Adaptivity/UnstructuredUniformRefinement.jl (hunk 1 above)
Comment (DimhamT) [reply src/Adaptivity/UnstructuredUniformRefinement.jl:4]: I'll remove this function.

File: src/Adaptivity/UnstructuredUniformRefinement.jl [hunk 2]
```diff
@@ -0,0 +1,545 @@
...
+3 ---- 6 ---- 4     |     3
+|      |      |     |     | \
+|      |      |     |     |  \
+7 ---- 9 ---- 8     |     5 - 6
+|      |      |     |     | \ |\
+|      |      |     |     |  \| \
+1 ---- 5 ---- 2     |     1 - 4 - 2
+      QUAD          |        TRI
+"""
+function cube_simplex_reference_grid(p::Polytope,n::Integer)
```
[the remark this answers is not in the document]
Comment (JordiManyer) [reply src/Adaptivity/UnstructuredUniformRefinement.jl:94]: Again, if you reused the stuff in RefinementRules you could get the fine-to-coarse topological maps without having to reorder anything, I think.

**Comment by DimhamT** [comment]
Hi, @JordiManyer . I recently refactored the code to make use of existing APIs for performing uniform refinement. In addition, I added functionality for refining periodic meshes.

The failing test is not related to the changes in this PR; it is caused by modifications introduced in a different PR.

**Comment by DimhamT** [comment]
Hi @JordiManyer  — just a gentle nudge on this PR.
When you have a moment, I’d love your review or any pointers on changes you’d like to see.
I’ve addressed the previous review feedback and pushed updates; please let me know if I missed anything.
Happy to revise, rebase, or split things up if that helps. Thanks!

<details>
  <summary>Screens & demo (3×)</summary>

**QUAD**
quad


**TRI**
tri

**HEX**
hex

** TET**
tet

**MOCK**
mock

**Periodic**
periodic

**Partial `[1,3,5]`**
partial


</details>

**Comment by JordiManyer** [comment]
Hi @DimhamT , thank you for the contribution. I think it looks good from my end. A couple simple changes before merging: 

- Since we are creating a new file for this, let's move all the code there. Can you move the methods that are currently in `AdaptedDiscreteModels.jl` and move them to the new file? Including the old `CartesianDiscreteModel` methods. 
- Within the `UniformRefinement` file, could you move the high-order API functions to the top? Just for ease of reading. 
- Can you add an entry to NEWS.md with the changes? 
- Don't forget to pull from master, I don't expect any issues. 

I'll merge the PR after that.

**Comment by DimhamT** [comment]
Hi, @JordiManyer . Thank you very much for the helpful feedback. I’ll make the corresponding changes and update the PR soon.

**Comment by DimhamT** [comment]
Hi, @JordiManyer . I’m not sure why one of the tests is failing here — all tests passed in my GitHub CI runs: [CI run link](https://github.com/DimhamT/Gridap.jl/actions/runs/18084677100).

**Comment by JordiManyer** [comment]
Thats OK, its memory issues because of 32-bit. Thanks for the contribution!
