### PR TITLE
Bugfix: get_normal_vector not correctly implemented for AdaptedTriangulations

### LINKED ISSUE #883: get_normal_vector with AdaptedTriangulation (atop BoundaryTriangulation) fails
Error with Gridap 0.17.17

MWE 

```
using Gridap
modelH = CartesianDiscreteModel((0,1,0,1),(2,2))
ΓH = BoundaryTriangulation(modelH)
get_normal_vector(ΓH) # ! OK!

modelh = Gridap.Adaptivity.refine(modelH)
Γh = BoundaryTriangulation(modelh)
get_normal_vector(Γh) # ! Crashes
```

Error report:

```

ERROR: AssertionError: This Grid does not have information about normals.
Stacktrace:
 [1] get_facet_normal(g::Gridap.Geometry.UnstructuredGrid{1, 2, Float64, Gridap.Geometry.NonOriented, Nothing})
   @ Gridap.Geometry ~/git-repos/Gridap.jl/src/Geometry/UnstructuredGrids.jl:114
 [2] get_facet_normal(grid::Gridap.Geometry.GridView{1, 2, Gridap.Geometry.UnstructuredGrid{1, 2, Float64, Gridap.Geometry.NonOriented, Nothing}, Vector{Int64}})
   @ Gridap.Geometry ~/git-repos/Gridap.jl/src/Geometry/GridPortions.jl:188
 [3] get_facet_normal(trian::Gridap.Adaptivity.AdaptedTriangulation{1, 2, BoundaryTriangulation{1, 2, Gridap.Geometry.BodyFittedTriangulation{1, 2, CartesianDiscreteModel{2, Float64, typeof(identity)}, Gridap.Geometry.GridView{1, 2, Gridap.Geometry.UnstructuredGrid{1, 2, Float64, Gridap.Geometry.NonOriented, Nothing}, Vector{Int64}}, Vector{Int64}}, Gridap.Geometry.FaceToCellGlue{Vector{Int64}, FillArrays.Fill{Int64, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Reindex{Vector{Int8}}, 1, Tuple{Base.OneTo{Int64}}}, Int8, 1, Tuple{Vector{Int64}}}, FillArrays.Fill{Int8, 1, Tuple{Base.OneTo{Int64}}}}}, Gridap.Adaptivity.AdaptedDiscreteModel{2, 2, CartesianDiscreteModel{2, Float64, typeof(identity)}, CartesianDiscreteModel{2, Float64, typeof(identity)}, Gridap.Adaptivity.AdaptivityGlue{Gridap.Adaptivity.RefinementGlue, 2, Vector{Vector{Int64}}, Vector{Int64}, FillArrays.Fill{Gridap.Adaptivity.RefinementRule{Gridap.ReferenceFEs.ExtrusionPolytope{2}, Gridap.Geometry.UnstructuredDiscreteModel{2, 2, Float64, Gridap.Geometry.Oriented}}, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.Table{Int64, Vector{Int64}, Vector{Int64}}, FillArrays.Fill{Bool, 1, Tuple{Base.OneTo{Int64}}}}}})
   @ Gridap.Geometry ~/git-repos/Gridap.jl/src/Geometry/Triangulations.jl:43
 [4] get_normal_vector(trian::Gridap.Adaptivity.AdaptedTriangulation{1, 2, BoundaryTriangulation{1, 2, Gridap.Geometry.BodyFittedTriangulation{1, 2, CartesianDiscreteModel{2, Float64, typeof(identity)}, Gridap.Geometry.GridView{1, 2, Gridap.Geometry.UnstructuredGrid{1, 2, Float64, Gridap.Geometry.NonOriented, Nothing}, Vector{Int64}}, Vector{Int64}}, Gridap.Geometry.FaceToCellGlue{Vector{Int64}, FillArrays.Fill{Int64, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.LazyArray{FillArrays.Fill{Reindex{Vector{Int8}}, 1, Tuple{Base.OneTo{Int64}}}, Int8, 1, Tuple{Vector{Int64}}}, FillArrays.Fill{Int8, 1, Tuple{Base.OneTo{Int64}}}}}, Gridap.Adaptivity.AdaptedDiscreteModel{2, 2, CartesianDiscreteModel{2, Float64, typeof(identity)}, CartesianDiscreteModel{2, Float64, typeof(identity)}, Gridap.Adaptivity.AdaptivityGlue{Gridap.Adaptivity.RefinementGlue, 2, Vector{Vector{Int64}}, Vector{Int64}, FillArrays.Fill{Gridap.Adaptivity.RefinementRule{Gridap.ReferenceFEs.ExtrusionPolytope{2}, Gridap.Geometry.UnstructuredDiscreteModel{2, 2, Float64, Gridap.Geometry.Oriented}}, 1, Tuple{Base.OneTo{Int64}}}, Gridap.Arrays.Table{Int64, Vector{Int64}, Vector{Int64}}, FillArrays.Fill{Bool, 1, Tuple{Base.OneTo{Int64}}}}}})
   @ Gridap.CellData ~/git-repos/Gridap.jl/src/CellData/CellFields.jl:108
 [5] top-level scope
   @ Untitled-2:8
```

Should be easy to fix. Just to implement the corresponding high-level API function.

### PR DESCRIPTION
**Pull request by JordiManyer**
Fixes #883

### CODE REVIEW

File: src/Adaptivity/AdaptedTriangulations.jl [hunk 1]
```diff
@@ -58,6 +58,10 @@ function Geometry.get_glue(t::AdaptedTriangulation,::Val{d}) where d
   get_glue(t.trian,Val(d))
 end
 
+function Geometry.get_facet_normal(trian::AdaptedTriangulation)
+  get_facet_normal(trian.trian)
```
Comment (amartinhuertas) [inline src/Adaptivity/AdaptedTriangulations.jl:62]: The background triangulation of the returned `CellField` object would be `trian.trian`, correct? 

Shouldn't it be `trian` instead?

Comment (JordiManyer) [reply src/Adaptivity/AdaptedTriangulations.jl:62]: No, `get_facet_normal` returns a lazy_array of fields. The lazy_array then gets wrapped into a CellField, which will have the desired triangulation. Note that I've redirected `get_facet_normal` instead of `get_normal_vector`.

Comment (JordiManyer) [reply src/Adaptivity/AdaptedTriangulations.jl:62]: I.e we have this 

```julia
function get_normal_vector(trian::Triangulation)
  cell_normal = get_facet_normal(trian)
  get_normal_vector(trian,cell_normal)
end

function get_normal_vector(trian::Triangulation,cell_normal::AbstractArray)
  GenericCellField(cell_normal,trian,ReferenceDomain())
end
```

Comment (amartinhuertas) [reply src/Adaptivity/AdaptedTriangulations.jl:62]: ok, thanks, understood, ready to merge when the tests pass ...

**Review by amartinhuertas — APPROVED** [review]
